// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"

	input "github.com/gabigontijo/Uol-teste/internal/usecases/ports/input"

	mock "github.com/stretchr/testify/mock"

	output "github.com/gabigontijo/Uol-teste/internal/usecases/ports/output"
)

// CreateClientUseCase is an autogenerated mock type for the CreateClientUseCase type
type CreateClientUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, createClient
func (_m *CreateClientUseCase) Execute(ctx context.Context, createClient *input.CreateClientInput) (*output.CreateClientOutput, error) {
	ret := _m.Called(ctx, createClient)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *output.CreateClientOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *input.CreateClientInput) (*output.CreateClientOutput, error)); ok {
		return rf(ctx, createClient)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *input.CreateClientInput) *output.CreateClientOutput); ok {
		r0 = rf(ctx, createClient)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*output.CreateClientOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *input.CreateClientInput) error); ok {
		r1 = rf(ctx, createClient)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCreateClientUseCase creates a new instance of CreateClientUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreateClientUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CreateClientUseCase {
	mock := &CreateClientUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
